### ISSUE TITLE
关于vscode提示代码错误的问题

### ISSUE THREAD

**Issue by bluefantasy728** [uniquemo/react-netease-music#10]
很好的react+ts的项目，能运行起来，但是为什么我vscode里会经常碰到代码提示错误，明明已经识别到是TypeScript React文件类型了。比如
![image](https://user-images.githubusercontent.com/17855282/91025142-94a45000-e62b-11ea-9fa7-dfca33ec72b8.png)
请问是我的vscode哪里配置的问题么？

**Comment by uniquemo** [comment]
> 很好的react+ts的项目，能运行起来，但是为什么我vscode里会经常碰到代码提示错误，明明已经识别到是TypeScript React文件类型了。比如
> ![image](https://user-images.githubusercontent.com/17855282/91025142-94a45000-e62b-11ea-9fa7-dfca33ec72b8.png)
> 请问是我的vscode哪里配置的问题么？

@bluefantasy728 应该是我的配置有问题，更新了一下eslint，你可以看看这个PR：https://github.com/uniquemo/react-netease-music/pull/11/files
