### ISSUE TITLE
yarn安装后启动报错

### ISSUE THREAD

**Issue by yangmuping** [uniquemo/react-netease-music#24]
$ node --trace-deprecation node_modules/.bin/webpack serve --mode=development
E:\reactProgram\wangyiMusic\react-netease-music\node_modules\.bin\webpack:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list

**Comment by uniquemo** [comment]
> $ node --trace-deprecation node_modules/.bin/webpack serve --mode=development
> E:\reactProgram\wangyiMusic\react-netease-music\node_modules.bin\webpack:2
> basedir=$(dirname "$(echo "$0" | sed -e 's,\,/,g')")
> ^^^^^^^
> 
> SyntaxError: missing ) after argument list

@yangmuping 可以试试删除node_modules重新安装喔，node版本最好使用12以上版本

**Comment by zhangle1** [comment]
我也是这个报错 是windows的原因吗

**Comment by zhangle1** [comment]
"start": "webpack serve --mode=development", 直接改成这样就好了
