### ISSUE TITLE
大佬 css的规则是需要引用什么识别吗

### ISSUE THREAD

**Issue by zhangle1** [uniquemo/react-netease-music#29]
@value constants: '~styles/constants.module.css';  
类似这样的 
我模仿你去些 好像@value 识别不到

**Comment by uniquemo** [comment]
@zhangle1 需要安装stylelint喔，可以尝试重启下vscode，有时候vscode识别比较慢

**Comment by zhangle1** [comment]
我就是想照着你的代码抄抄改改 ，但是我新开得那个 @value 提示无法识别....      也不知道要怎么操作一下 webpack 和package.json 都是拿过来的..
