### ISSUE TITLE
老哥，你网站挂了

### ISSUE THREAD

**Issue by inspire-lts** [uniquemo/react-netease-music#39]

**Comment by uniquemo** [comment]
可以打开啊，www.uniquemo.cn @inspire-lts

**Comment by inspire-lts** [comment]
@uniquemo  我打开是没有备案 不能显示
![image](https://user-images.githubusercontent.com/33800259/124631447-f8d3a980-deb5-11eb-9233-fc448d491b32.png)

**Comment by uniquemo** [comment]
@inspire-lts 好的，我抽空处理一下~

**Comment by uniquemo** [comment]
@inspire-lts 我把域名迁移了，请问下现在你能访问到吗？

**Comment by inspire-lts** [comment]
@uniquemo 还是这个域名吗www.uniquemo.cn 依旧是没备案访问不了

**Comment by uniquemo** [comment]
> @uniquemo 还是这个域名吗www.uniquemo.cn 依旧是没备案访问不了

@inspire-lts 是的，现在应该可以访问了
