### ISSUE TITLE
hooks中useAsyncFn.ts的问题

### ISSUE THREAD

**Issue by Kitaharakasusa** [uniquemo/react-netease-music#9]
没看懂这个地方是在干嘛，为什么每一个异步请求函数都用这个钩子包了一下呀，望解惑，谢谢。

**Comment by uniquemo** [comment]
> 没看懂这个地方是在干嘛，为什么每一个异步请求函数都用这个钩子包了一下呀，望解惑，谢谢。

@Kitaharakasusa 这个hook是用来复用发起请求时获取loading状态、error、data信息的逻辑的。
